config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :preupgrade_reports, :only => %i[index]

  namespace :api, defaults: { format: 'json' } do
    scope '(:apiv)', module: :v2, defaults: { apiv: 'v2' }, apiv: /v2/,
          constraints: ApiConstraints.new( version: 2, default: true) do
      resources :preupgrade_reports, only: %i[index show]
      get 'job_invocations/:id/preupgrade_reports', to: 'preupgrade_reports#job_invocation'
    end
  end
end

app/models/concerns/foreman_leapp/job_invocation_extensions.rb
# frozen_string_literal: true

module ForemanLeapp
  module JobInvocationExtensions
    extend ActiveSupport::Concern

    included do
      has_many :preupgrade_reports, dependent: :destroy
    end
  end
end

app/models/preupgrade_report.rb
# frozen_string_literal: true

class PreupgradeReport < ::Report
  belongs_to :job_invocation
  has_many :preupgrade_report_entries, dependent: :destroy

  scoped_search on: :job_invocation_id, only_explicit: true

  def self.create_report(host, data, job_invocation_id)
    report = PreupgradeReport.create(host: host, status: 0,
                                     job_invocation_id: job_invocation_id,
                                     reported_at: DateTime.now.utc)

    data['entries']&.each do |entry|
      PreupgradeReportEntry.create! entry_params(report, entry, host, data)
    end
  end

  def self.entry_params(report, entry, host, data)
    { preupgrade_report: report,
      host_id: host.id,
      hostname: host.name,
      title: entry['title'],
      actor: entry['actor'],
      audience: entry['audience'],
      severity: entry['severity'],
      leapp_run_id: data['leapp_run_id'],
      summary: entry['summary'],
      tags: entry['tags'],
      flags: entry['flags'],
      detail: entry['detail'] }
  end
end

app/models/preupgrade_report_entry.rb
# frozen_string_literal: true

class PreupgradeReportEntry < ApplicationRecord
  belongs_to :preupgrade_report
  belongs_to_host

  serialize :tags, Array
  serialize :flags, Array
  serialize :detail, JSON

  validates :preupgrade_report, :host, :hostname, :title, :actor, :audience, :severity, :leapp_run_id, presence: true

  def self.remediation_details(remediation_ids, host)
    where(id: remediation_ids, host: host).where.not(detail: nil).pluck(:detail)
  end
end

app/controllers/api/v2/concerns/api_authorizer.rb
# frozen_string_literal: true

module ApiAuthorizer
  extend ActiveSupport::Concern

  included do
    before_action :hosts_permission
  end

  private

  def hosts_permission
    return if User.current.can?('view_hosts')

    render_error 'access_denied', status: :forbidden,
                                  locals: { details: _('Missing one of the required permissions: view_hosts'),
                                            missing_permissions: 'view_hosts' }
  end

  def resource_scope(_options = {})
    @resource_scope ||= begin
      scope = PreupgradeReport.joins(:host).merge(Host.authorized(:view_hosts, Host))
      scope = scope.where(job_invocation_id: params[:id]) if action_name == 'job_invocation'
      scope
    end
  end
end

app/controllers/api/v2/preupgrade_reports_controller.rb
# frozen_string_literal: true

module Api
  module V2
    class PreupgradeReportsController < ::Api::V2::BaseController
      include ApiAuthorizer

      layout 'api/v2/layouts/index_layout', except: %i[show]

      api :GET, '/preupgrade_reports/', N_('List Preupgrade reports')
      param_group :search_and_pagination, ::Api::V2::BaseController
      def index
        @preupgrade_reports = resource_scope_for_index
      end

      api :GET, '/preupgrade_reports/:id', N_('Show Preupgrade report')
      param :id, :identifier, required: true
      def show
        @preupgrade_report = resource_scope.find(params[:id])
      end

      api :GET, '/job_invocations/:id/preupgrade_reports', N_('List Preupgrade reports for Job invocation')
      param :id, :identifier, required: true
      def job_invocation
        @preupgrade_reports = resource_scope_for_index.where(job_invocation_id: params[:id])
      end

      private

      # By overriding path_to_authenticate we can require REX's permission view_job_invocations
      def path_to_authenticate
        params['action'] = 'show' if params['action'] == 'job_invocation'
        Foreman::AccessControl.normalize_path_hash params.slice(:action, :id, :user_id)
                                                         .merge({ controller: 'api/v2/job_invocations' })
      end
    end
  end
end

app/controllers/preupgrade_reports_controller.rb
# frozen_string_literal: true

class PreupgradeReportsController < ::Api::V2::BaseController
  include ApiAuthorizer

  def index
    @preupgrade_reports = resource_scope.includes(:preupgrade_report_entries).search_for(*search_options)
  end

  private

  # By overriding :path_to_authenticate we can require REX's :view_job_invocations permission
  def path_to_authenticate
    Foreman::AccessControl.normalize_path_hash params.slice(:action, :id, :user_id)
                                                     .merge({ controller: 'job_invocations' })
  end
end

app/helpers/concerns/foreman_leapp/remote_execution_helper_extension.rb
# frozen_string_literal: true

module ForemanLeapp
  module RemoteExecutionHelperExtension
    def rex_host_features(*args)
      super + [link_to(_('Preupgrade check with Leapp'),
                       new_job_invocation_path(host_ids: [args.first.id], feature: 'leapp_preupgrade')),
               link_to(_('Upgrade with Leapp'),
                       new_job_invocation_path(host_ids: [args.first.id], feature: 'leapp_upgrade'))]
    end
  end
end

app/helpers/foreman_leapp/hosts_helper.rb
# frozen_string_literal: true

module ForemanLeapp
  module HostsHelper
    def leapp_hosts_multiple_actions
      [{ action: [_('Preupgrade check with Leapp'), new_job_invocation_path(feature: 'leapp_preupgrade'), false],
         priority: 1000 },
       { action: [_('Upgrade with Leapp'), new_job_invocation_path(feature: 'leapp_upgrade'), false], priority: 1000 }]
    end
  end
end

app/helpers/foreman_leapp/template_helper.rb
# frozen_string_literal: true

module ForemanLeapp
  module TemplateHelper
    def build_remediation_plan(remediation_ids, host)
      PreupgradeReportEntry.remediation_details(remediation_ids, host)
                           .map { |e| e['remediations'] }
                           .flatten
                           .compact
                           .select { |r| r['type'] == 'command' }
                           .map { |r| "#{r['context'].join(' ')}\n" }
                           .join
    end
  end
end

app/views/foreman_leapp/job_templates/leapp_check.erb
<%#
name: Check Leapp
description_format: 'Check if Leapp package is installed.'
kind: job_template
job_category: Leapp
provider_type: SSH
snippet: true
model: JobTemplate
%>

if ! command -v leapp > /dev/null
then
  echo "Leapp is not installed."
  exit 1
fi

app/views/foreman_leapp/job_templates/leapp_preupgrade.erb
<%#
kind: job_template
name: Run preupgrade via Leapp
job_category: Leapp - Preupgrade
description_format: 'Upgradeability check for RHEL 7 host'
provider_type: SSH
feature: leapp_preupgrade
model: JobTemplate
%>

<%= render_template 'Check Leapp' %>

rm -f /var/log/leapp/leapp-report.json
leapp preupgrade

echo "===leap_upgrade_report_start==="
cat /var/log/leapp/leapp-report.json

app/views/foreman_leapp/job_templates/leapp_remediation.erb
<%#
kind: job_template
name: Run remediation plan via Leapp
job_category: Other
description_format: 'Run remediation plan via Leapp'
provider_type: SSH
feature: leapp_remediation_plan
model: JobTemplate
template_inputs:
- name: remediation_ids
  required: true
  advanced: true
  input_type: user
  value_type: plain
  description: List of remediation ids
- name: run_preupgrade
  description: Run preupgrade check again when remediation entries are fixed.
  input_type: user
  required: true
  options: "true\nfalse"
  default: "true"
%>

<%= render_template 'Check Leapp' %>

<%= build_remediation_plan(input('remediation_ids').split(','), @host) %>
<% if input('run_preupgrade') == 'true' %>
  <%= render_template 'Run preupgrade via Leapp' %>
<% end %>

app/views/foreman_leapp/job_templates/leapp_upgrade.erb
<%#
kind: job_template
name: Run upgrade via Leapp
job_category: Leapp - Upgrade
description_format: 'Upgrade RHEL 7 host'
provider_type: Ansible
feature: leapp_upgrade
model: JobTemplate
template_inputs:
- name: Reboot
  description: Reboot the host automaticaly to continue with the upgrade
  input_type: user
  required: true
  default: "true"
  options: "true\nfalse"
%>
---
- hosts: all
  tasks:
    - name: Run Leapp Upgrade
      command: leapp upgrade
<%- if input('Reboot') == "true" -%>
    - name: Reboot the machine
      reboot:
        reboot_timeout: 1800
<%- end -%>

app/views/job_invocations/_leapp_preupgrade_report.html.erb
<% content_for(:javascripts) do %>
  <%= webpacked_plugins_js_for :foreman_leapp %>
<% end %>
<% content_for(:stylesheets) do %>
  <%= webpacked_plugins_css_for :foreman_leapp %>
<% end %>

<%= react_component('PreupgradeReports', {
  :url => preupgrade_reports_path(:search => "job_invocation_id = #{@job_invocation.id}"),
  :newJobInvocationUrl => new_job_invocation_path
}) %>